### ISSUE TITLE
您好，refreshSlider调用报错呢。不知道SliderInfo是要怎么个赋值法？

### ISSUE THREAD

**Issue by andansky** [hss01248/ImageSliderByFresco#1]
android.view.InflateException: Binary XML file line #5: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:639)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:812)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:510)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:420)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:371)
                                                                            at com.hss01248.slider.SliderTypes.DefaultSliderView.getView(DefaultSliderView.java:23)
                                                                            at com.hss01248.slider.SliderAdapter.instantiateItem(SliderAdapter.java:81)
                                                                            at com.hss01248.slider.Tricks.InfinitePagerAdapter.instantiateItem(InfinitePagerAdapter.java:55)
                                                                            at com.hss01248.slider.Tricks.ViewPagerEx.addNewItem(ViewPagerEx.java:848)
                                                                            at com.hss01248.slider.Tricks.ViewPagerEx.populate(ViewPagerEx.java:998)
                                                                            at com.hss01248.slider.Tricks.ViewPagerEx.setCurrentItemInternal(ViewPagerEx.java:562)
                                                                            at com.hss01248.slider.Tricks.ViewPagerEx.setCurrentItemInternal(ViewPagerEx.java:526)
                                                                            at com.hss01248.slider.Tricks.ViewPagerEx.setCurrentItem(ViewPagerEx.java:507)
                                                                            at com.hss01248.slider.Indicators.PagerIndicator$1.onChanged(PagerIndicator.java:411)
                                                                            at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
                                                                            at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:287)
                                                                            at com.hss01248.slider.SliderAdapter.addSlider(SliderAdapter.java:28)
                                                                            at com.hss01248.slider.SliderLayout.addSlider(SliderLayout.java:255)
                                                                            at com.xinji.jugongyouyue.fragment.HomeFragment.initSlideView(HomeFragment.java:316)
                                                                            at com.xinji.jugongyouyue.fragment.HomeFragment.initView(HomeFragment.java:272)
                                                                            at com.andan.presenter.HomeFragPresenterImpl.onSuccess(HomeFragPresenterImpl.java:31)
                                                                            at com.andan.model.HomeFragModelImpl$1.onCacheSuccess(HomeFragModelImpl.java:77)
                                                                            at com.andan.model.HomeFragModelImpl$1.onCacheSuccess(HomeFragModelImpl.java:69)
                                                                            at com.lzy.okgo.adapter.CacheCall$3.run(CacheCall.java:234)
                                                                            at android.os.Handler.handleCallback(Handler.java:815)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                            at android.os.Looper.loop(Looper.java:192)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5878)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1089)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:855)
                                                                         Caused by: java.lang.reflect.InvocationTargetException
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:812) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:510) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:420) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:371) 
                                                                            at com.hss01248.slider.SliderTypes.DefaultSliderView.getView(DefaultSliderView.java:23) 
                                                                            at com.hss01248.slider.SliderAdapter.instantiateItem(SliderAdapter.java:81) 
                                                                            at com.hss01248.slider.Tricks.InfinitePagerAdapter.instantiateItem(InfinitePagerAdapter.java:55) 
                                                                            at com.hss01248.slider.Tricks.ViewPagerEx.addNewItem(ViewPagerEx.java:848) 
                                                                            at com.hss01248.slider.Tricks.ViewPagerEx.populate(ViewPagerEx.java:998)

**Comment by andansky** [comment]
我知道了，这个是因为我没初始化Fresco.
